export const AUTH = {
  LOGIN: "LOGIN",
  LOGIN_ADMIN: "LOGIN_ADMIN",
  FETCH_USER_LOGIN: "FETCH_USER_LOGIN",
  ADMIN_RECOVER_PASSWORD: "ADMIN_RECOVER_PASSWORD",
  ADMIN_RESET_PASSWORD: "ADMIN_RESET_PASSWORD",
  LOG_OUT: "ADMIN_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
};

export const ADMIN = {
  GET_ME: "ADMIN_GET_ME",
  GET_USER_LIST: "ADMIN_GET_USER_LIST",
  GET_USER_DETAIL: "ADMIN_GET_USER_DETAIL",
  GET_OVERVIEW: "ADMIN_GET_OVERVIEW",
  DELETE_USERS: "ADMIN_DELETE_USER",
};

export const COUNTER = {
  FETCH_COUNTER: "FETCH_COUNTER",
};
